### ISSUE TITLE
ACTION REQUIRED: Changes to pulling Chainguard Images

### ISSUE THREAD

**Issue by chainguard-alerter** [airlock/microgateway#2]
Hey there [Chainguard](https://github.com/chainguard-dev) here.

We noticed that you are using [Chainguard Images](https://github.com/chainguard-images/images), thank you! We wanted to make you aware of an upcoming change that will impact your project.

Starting August 16, 2023 public users will no longer be able to pull images from our registry (cgr.dev/chainguard) by tags other than `latest` or `latest-dev`. Please see [the announcement](https://www.chainguard.dev/unchained/scaling-chainguard-images-with-a-growing-catalog-and-proactive-security-updates) for more information.

You are currently using the following.

In https://github.com/airlock/microgateway/blob/0cd844dea1c9599baebb58fc0d3dcd42b51d66a8/deploy/deployment/Deployment_airlock-microgateway-license-guard-redis.yaml:

- cgr.dev/chainguard/redis:7.0.11

Our goal is to prevent your project from experiencing any disruptions. Please see [the migration guide](https://www.chainguard.dev/unchained/a-guide-on-how-to-use-chainguard-images-for-public-catalog-tier-users) for options.

If there's more we can do to help please reply to this issue or email us at [support@chainguard.dev](mailto:support@chainguard.dev).

Thank you!

**Comment by nbam-e** [comment]
This is most likely a false positive. The specified image is pulled by digest (the tag in the image ref was only left there for informational purposes) and should thus not be affected by the Chainguard changes.

To make it more explicit that the image is pulled by digest and avoid future confusion, the image tag has been removed in 4.0.1.

**Comment by amouat** [comment]
Yes, you're right. If you're using a digest you will be unaffected (and in fact the tag is ignored when pulling the image).
